'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, MapPin, Heart, House, Footprints, Trees, Users, CalendarDays, Menu, X, Mail } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
export const pageTitles: Record<string,string> = {about:'About Mohamed',priorities:'Our priorities','priorities/housing':'Homes people can afford','priorities/safer-streets':'Safer streets, connected neighbourhoods','priorities/public-spaces':'Parks and public spaces','ward-9':'Our Ward 9',volunteer:'Volunteer','request-a-sign':'Request a sign',donate:'Donate',endorse:'Endorse Mohamed',vote:'Make your voice count',updates:'Campaign updates',contact:'Let’s talk'};
const election='https://www.kitchener.ca/council-and-city-administration/election/';
const mapUrl='https://app2.kitchener.ca/appdocs/GISImages/GIS_Web_External/Standard_Maps/Ward_map_small.pdf';
const park='/victoria-park.jpg';
const priorities=[{slug:'housing',icon:House,title:'Homes people can afford.',text:'A place to put down roots. A neighbourhood where people can stay.',points:['Explore a wider range of homes close to everyday services.','Consider affordability and accessibility as our neighbourhoods grow.','Listen to renters, homeowners, and people looking for a home.']},{slug:'safer-streets',icon:Footprints,title:'Streets that connect us.',text:'Safer walks, easier connections, and streets that work for everyone.',points:['Identify difficult crossings with residents.','Explore safer routes to schools, parks, and local destinations.','Consider accessibility for every age and ability.']},{slug:'public-spaces',icon:Trees,title:'Places to come together.',text:'Welcoming parks and shared spaces. A stronger sense of belonging.',points:['Listen to how neighbours use local parks and gathering places.','Explore accessible, well-maintained public spaces.','Support conversations about trees, shade, and community connections.']}];
function LinkButton({href,children,light=false}: {href:string;children:React.ReactNode;light?:boolean}) {return <a className={`button ${light?'light':''}`} href={href}>{children}<ArrowUpRight size={18}/></a>}
function Label({children}: {children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
function Header(){const [open,setOpen]=useState(false);return <><a className="skip" href="#main">Skip to content</a><header className="header"><a className="brand" href="/" aria-label="Mohamed Askalany home"><span>MOHAMED</span><strong>ASKALANY<span className="brand-dot">.</span></strong><small>KITCHENER CITY COUNCIL · WARD 9</small></a><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="navigation" aria-label={open?'Close navigation':'Open navigation'}>{open?<X/>:<Menu/>}</button><nav id="navigation" className={open?'nav open':'nav'} aria-label="Main navigation"><a href="/about">Meet Mohamed</a><a href="/priorities">Priorities</a><a href="/ward-9">Ward 9</a><a href="/volunteer">Get involved</a><a href="/vote">Vote</a><a className="nav-donate" href="/donate">Donate <Heart size={15}/></a></nav></header></>}
function Hero(){return <section className="hero"><div className="hero-copy"><Label><span className="status-dot"/> YOUR NEIGHBOUR. YOUR VOICE. WARD 9.</Label><h1>A stronger<br/>community.<br/><em>Together.</em></h1><p>I’m Mohamed Askalany, candidate for Kitchener City Council, Ward 9. Let’s build a neighbourhood where we can all belong.</p><div className="actions"><LinkButton href="/about">Meet Mohamed</LinkButton><a className="text-link" href="/volunteer">Join the team <ArrowRight size={18}/></a></div><div className="hero-foot"><MapPin size={16}/> Rooted in community. Focused on Ward 9.</div></div><div className="hero-image"><img src="/mohamed-askalany.png" alt="Mohamed Askalany smiling and holding a Canadian flag" fetchPriority="high"/><div className="portrait-caption"><span>MOHAMED ASKALANY</span><small>For Kitchener City Council · Ward 9</small></div><div className="ward-stamp"><span>FOR</span><strong>WARD 9</strong><span>FOR ALL OF US.</span></div></div></section>}
function Why(){return <section className="section why"><Label>WHY I’M RUNNING</Label><div><h2>Good local government<br/>starts with <em>listening.</em></h2><p>Our streets, our parks, the places we call home. The decisions made at City Hall shape our everyday lives. This campaign starts with a simple idea: neighbours should have a voice in those decisions.</p><a className="text-link" href="/about">Get to know Mohamed <ArrowUpRight size={19}/></a></div></section>}
function Experience(){return <section className="experience section"><div><Label>THE PERSON BEHIND THE CAMPAIGN</Label><h2>People first.<br/>Purpose always.</h2></div><div><p>A closer look at Mohamed’s background, professional experience, and community involvement.</p><p className="pending">Mohamed’s verified biography and credentials will be shared here following campaign review.</p><a className="text-link" href="/about">More about Mohamed <ArrowUpRight size={18}/></a></div></section>}
function PriorityCards(){return <div className="priority-grid">{priorities.map((p,i)=><a className="priority-card" href={'/priorities/'+p.slug} key={p.slug}><div className="card-top"><p.icon size={29} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{p.title}</h3><p>{p.text}</p><span className="card-link">Explore the priority <ArrowUpRight size={20}/></span></a>)}</div>}
function Priorities(){return <section className="section priorities"><div className="section-heading"><div><Label>EVERYDAY ISSUES. LOCAL SOLUTIONS.</Label><h2>A better everyday.<br/>For all of us.</h2></div><a className="text-link" href="/priorities">Explore our priorities <ArrowUpRight size={19}/></a></div><p className="draft-label">Proposed discussion themes · subject to campaign approval</p><PriorityCards/></section>}
function WardMap(){return <section className="section ward-section"><div className="map-frame"><iframe title="Map of central Kitchener around Victoria Park; use the official map to verify Ward 9 boundaries" src="https://www.openstreetmap.org/export/embed.html?bbox=-80.516%2C43.433%2C-80.481%2C43.458&layer=mapnik" loading="lazy"/><span className="map-tag"><MapPin size={17}/> GET TO KNOW WARD 9</span></div><div><Label>OUR NEIGHBOURHOOD</Label><h2>Many stories.<br/>One Ward 9.</h2><p>From a walk through Victoria Park to a conversation with a neighbour, community happens in the places we share.</p><p>Find your ward and explore the streets and spaces around us.</p><LinkButton href="/ward-9">Explore Ward 9</LinkButton><a className="sub-link" href={mapUrl} target="_blank" rel="noreferrer">View official ward boundaries ↗</a><small className="map-note">Neighbourhood map shown; ward boundaries are on the City’s official map.</small></div></section>}
function Story(){return <section className="story"><div className="story-photo"><img src={park} alt="The lake and pavilion at Victoria Park in Kitchener" loading="lazy"/><span>VICTORIA PARK, KITCHENER</span></div><div className="story-copy"><Label>IT STARTS RIGHT HERE</Label><h2>A community isn’t<br/>just where we live.<br/><em>It’s what we build.</em></h2><p>Every neighbour has a story. Every conversation brings a new perspective. Let’s make space for yours.</p><LinkButton href="/contact" light>Share your perspective</LinkButton></div></section>}
function EndorsementCard({quote,name}: {quote?:string;name?:string}){return <article className="endorsement-card"><span className="quote-mark">“</span>{quote?<><blockquote>{quote}</blockquote><p>{name}</p></>:<><h3>Trust grows neighbour<br/>by neighbour.</h3><p>Community endorsements will appear here once confirmed and approved for publication.</p><a className="text-link" href="/endorse">Add your voice <ArrowUpRight size={18}/></a></>}</article>}
function Endorsements(){return <section className="section endorsements"><div><Label>COMMUNITY VOICES</Label><h2>Better, with<br/><em>your support.</em></h2><p>Know Mohamed? Share why you’re supporting his campaign for Ward 9.</p></div><EndorsementCard/></section>}
function GetInvolved(){return <section className="section involved"><Label>THERE’S A PLACE FOR YOU HERE</Label><h2>Small actions.<br/>A stronger community.</h2><div className="involved-grid">{[{title:'Lend a hand',text:'Bring your time, your ideas, and your neighbourly spirit.',href:'/volunteer',label:'Volunteer',icon:Users},{title:'Show your support',text:'Make a little room for Ward 9 on your front lawn.',href:'/request-a-sign',label:'Request a sign',icon:House},{title:'Help us reach further',text:'Support the work of connecting with our neighbours.',href:'/donate',label:'Donate',icon:Heart}].map(a=><article key={a.href}><a.icon size={27}/><h3>{a.title}</h3><p>{a.text}</p><a className="text-link" href={a.href}>{a.label}<ArrowUpRight size={19}/></a></article>)}</div></section>}
function Updates(){return <section className="section updates"><div className="section-heading"><div><Label>ON THE CAMPAIGN TRAIL</Label><h2>What’s happening.</h2></div><a className="text-link" href="/updates">All updates <ArrowUpRight size={18}/></a></div><div className="update-row"><span className="update-icon"><Mail size={27}/></span><div><Label>STAY CONNECTED</Label><h3>The next chapter starts here.</h3><p>Campaign news, neighbourhood conversations, and upcoming events will be posted here.</p></div><a className="circle-link" href="/updates" aria-label="Read campaign updates"><ArrowUpRight/></a></div></section>}
function VotingInfo(){return <section className="section vote-section"><div className="vote-date"><CalendarDays size={28}/><span>OCTOBER</span><strong>26</strong><span>MONDAY · 2026</span></div><div><Label>YOUR WARD. YOUR VOICE. YOUR VOTE.</Label><h2>Let’s shape what’s next.</h2><p>Kitchener’s municipal election is Monday, October 26, 2026. Find official information on registration, locations, and how to vote.</p><LinkButton href="/vote">Make your voting plan</LinkButton></div></section>}
function CampaignForm({kind='newsletter'}:{kind?:string}){const [status,setStatus]=useState('');const [consent,setConsent]=useState(false);const newsletter=kind==='newsletter';return <form className="campaign-form" onSubmit={e=>{e.preventDefault();setStatus('This preview is not accepting submissions yet. Your information has not been sent or saved. Please return when the campaign’s contact service is connected.');}}><p className="form-notice">Preview form · submissions are not yet open.</p><div className="form-grid"><label>First name<Input name="firstName" autoComplete="given-name" required/></label>{!newsletter&&<label>Last name<Input name="lastName" autoComplete="family-name" required/></label>}<label>Email address<Input name="email" type="email" autoComplete="email" required/></label>{kind==='request-a-sign'&&<><label className="full">Street address<Input name="address" autoComplete="street-address" required/></label><label>Postal code<Input name="postalCode" autoComplete="postal-code" required/></label></>}{kind==='volunteer'&&<fieldset className="full"><legend>How would you like to help?</legend>{['Canvassing with the team','Delivering campaign materials','Events and community outreach','Other / wherever needed'].map((s,i)=><label className="check-row" key={s}><Checkbox name={'interest-'+i}/>{s}</label>)}</fieldset>}{!newsletter&&kind!=='request-a-sign'&&<label className="full">{kind==='endorse'?'Why are you supporting Mohamed?':'Your message'}<textarea name="message" rows={4} required={kind==='endorse'||kind==='contact'}/></label>}</div><label className="check-row consent"><Checkbox required checked={consent} onCheckedChange={v=>setConsent(!!v)}/><span>{newsletter?'I agree to receive campaign email updates. I can unsubscribe at any time.':kind==='endorse'?'I consent to being contacted to confirm my endorsement before anything is published.':'I consent to the campaign contacting me about this request.'}</span></label><button className="button" type="submit" disabled={!consent}>{newsletter?'Join the mailing list':'Review request'}<ArrowRight size={18}/></button><p role="status" className="form-status">{status}</p></form>}
function Newsletter(){return <section className="section newsletter"><div><Label>GOOD THINGS START WITH A CONVERSATION</Label><h2>Let’s stay<br/><em>in touch.</em></h2><p>Be part of what’s next for Ward 9.<br/>Campaign news, events, and ways to help.</p></div><CampaignForm/></section>}
function Footer(){return <footer className="footer"><div className="footer-main"><a className="brand" href="/"><span>MOHAMED</span><strong>ASKALANY.</strong><small>FOR KITCHENER CITY COUNCIL · WARD 9</small></a><p>A stronger community.<br/>Together.</p><div>{['about','priorities','ward-9','vote','updates','contact'].map(p=><a key={p} href={'/'+p}>{pageTitles[p]}</a>)}</div><div>{['volunteer','request-a-sign','donate','endorse'].map(p=><a key={p} href={'/'+p}>{pageTitles[p]}</a>)}</div></div><div className="footer-bottom"><span>© 2026 Mohamed Askalany campaign · Private campaign preview</span><span>Made for our community.</span></div><p className="photo-credit">Victoria Park photograph: <a href="https://commons.wikimedia.org/wiki/File:Victoria-park-kitchener-lake.jpg">Lupin / Wikimedia Commons</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a> (displayed cropped). Map © OpenStreetMap contributors.</p></footer>}
function PageIntro({slug,kicker,text}:{slug:string;kicker:string;text:string}){return <section className="page-intro section"><a className="breadcrumb" href="/">Home /</a><Label>{kicker}</Label><h1>{pageTitles[slug]}<span className="accent">.</span></h1><p>{text}</p></section>}
function InnerPage({slug}:{slug:string}){const priority=priorities.find(p=>'priorities/'+p.slug===slug);if(priority)return <><PageIntro slug={slug} kicker="OUR PRIORITIES" text={priority.text}/><section className="section policy"><p className="pending">Draft discussion theme. These ideas are awaiting campaign approval and are not confirmed policy commitments.</p><h2>A conversation about<br/>our everyday lives.</h2><p>Good decisions start with understanding what people experience in their neighbourhood. This is a space to explore practical ideas with Ward 9 residents.</p>{priority.points.map((p,i)=><div className="policy-point" key={p}><span>0{i+1}</span><h3>{p}</h3></div>)}<LinkButton href="/contact">Share what matters to you</LinkButton></section><section className="section"><Label>EXPLORE THE OTHER PRIORITIES</Label><PriorityCards/></section></>;
if(slug==='about')return <><PageIntro slug={slug} kicker="MEET YOUR CANDIDATE" text="Mohamed Askalany is a candidate for Kitchener City Council, Ward 9."/><section className="section about-grid"><img src="/mohamed-askalany.png" alt="Mohamed Askalany holding a Canadian flag"/><div><h2>A campaign built<br/>around community.</h2><p>Meet the person behind the name and learn what brings him to this campaign.</p><p className="pending">Mohamed’s personal story, work history, qualifications, and connection to Ward 9 are awaiting verified campaign copy.</p><LinkButton href="/contact">Start a conversation</LinkButton></div></section><Why/><Experience/></>;
if(slug==='priorities')return <><PageIntro slug={slug} kicker="A BETTER EVERYDAY" text="Explore the local issues that shape the places we live, move, and come together."/><section className="section"><p className="pending">These proposed discussion themes are awaiting campaign approval.</p><PriorityCards/></section><GetInvolved/></>;
if(slug==='ward-9')return <><PageIntro slug={slug} kicker="THIS PLACE WE SHARE" text="Explore the neighbourhood, find your ward, and tell us what matters on your street."/><WardMap/><section className="section"><h2>Are you in Ward 9?</h2><p>Use your address in the City’s official ward finder to confirm your ward. The neighbourhood map on this site does not show election boundaries.</p><LinkButton href="https://app2.kitchener.ca/city_hall/findward.aspx">Find my ward</LinkButton></section><Story/></>;
if(slug==='vote')return <><PageIntro slug={slug} kicker="KITCHENER MUNICIPAL ELECTION · 2026" text="Make a plan to have your say in your city’s future."/><VotingInfo/><section className="section vote-steps">{[{title:'Check your voter information',text:'Use the City’s official resources to check registration and eligibility.',href:election+'voter-information/'},{title:'Find where and when to vote',text:'Confirm your voting location and available voting opportunities with the City.',href:election+'where-to-vote/'},{title:'Plan ahead',text:'Review the City’s identification and accessibility information before you go.',href:election+'voter-information/'}].map((s,i)=><article key={s.title}><span className="step-number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><a className="text-link" href={s.href}>Official information <ArrowUpRight size={18}/></a></article>)}<p>Election date source: <a href={election}>City of Kitchener</a>. Always check the City for the latest election details.</p></section></>;
if(slug==='updates')return <><PageIntro slug={slug} kicker="FROM THE CAMPAIGN" text="News, conversations, and ways to connect with Mohamed and the team."/><section className="section empty-news"><Mail size={36}/><h2>More to share soon.</h2><p>No campaign updates have been published yet. Join the mailing list to hear when news and events are announced.</p><a className="text-link" href="#newsletter">Stay in the loop <ArrowRight size={18}/></a></section></>;
if(slug==='donate')return <><PageIntro slug={slug} kicker="HELP THE CAMPAIGN REACH OUR NEIGHBOURS" text="Your support can help bring more conversations to more doorsteps."/><section className="section form-page"><div><Heart size={38}/><h2>Make a difference<br/>close to home.</h2><p>Campaign contributions help support local outreach and campaign materials.</p></div><div className="donate-panel"><h3>Donations are not open yet.</h3><p>A verified, secure campaign donation link will be added here when available.</p><p>No payment information is collected on this website.</p><LinkButton href="/volunteer">Give your time instead</LinkButton></div></section></>;
const info: Record<string,{kicker:string;text:string;heading:string;body:string}>={volunteer:{kicker:'LET’S DO THIS TOGETHER',text:'A little of your time can go a long way. Find your place on the team.',heading:'Everyone has something to bring.',body:'Whether you enjoy meeting neighbours, helping at events, or working behind the scenes, there’s a way to contribute. Let us know your interests and availability.'},'request-a-sign':{kicker:'SHOW YOUR SUPPORT',text:'Bring the campaign to your street with a Mohamed Askalany lawn sign.',heading:'A small sign. A visible show of support.',body:'Share your address and the campaign will follow up about sign availability and delivery once requests open.'},endorse:{kicker:'ADD YOUR VOICE',text:'Tell your neighbours why you support Mohamed.',heading:'Your words matter.',body:'Share your experience in your own words. The campaign will confirm permission and attribution before publishing an endorsement.'},contact:{kicker:'WE’RE LISTENING',text:'A question, an idea, or something happening on your street? Start here.',heading:'Let’s talk about Ward 9.',body:'Tell us what’s on your mind. Campaign contact details and message delivery are being finalized.'}};
const d=info[slug];return <><PageIntro slug={slug} kicker={d.kicker} text={d.text}/><section className="section form-page"><div><h2>{d.heading}</h2><p>{d.body}</p></div><CampaignForm kind={slug}/></section></>;
}
export function CampaignPage({slug}:{slug:string}){return <><Header/><main id="main">{slug==='home'?<><Hero/><Why/><Experience/><Priorities/><WardMap/><Story/><Endorsements/><GetInvolved/><Updates/><VotingInfo/></>:<InnerPage slug={slug}/>}<div id="newsletter"><Newsletter/></div></main><Footer/></>}
